runcharts:
  - title: Ping google.com
    position: [[0, 1], [80, 20]]
    rate-ms: 1000
    legend:
        enabled: false
        details: false
    scale: 2
    items:
      - label: google.com
        sample: ping -c 1 www.google.com | tail -1| awk '{print $4}' | cut -d '/'
            -f 2
textboxes:
  - title: Docker containers stats
    position: [[0, 21], [80, 21]]
    rate-ms: 500
    sample: docker stats --no-stream --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.PIDs}}"
