runcharts:
  - title: Bitcoin price
    position: [[0, 20], [80, 21]]
    rate-ms: 300000
    legend:
        enabled: false
        details: false
    scale: 0
    items:
      - label: Bitcoin
        sample: curl -s "https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT" |
            jq '.price' | sed -e 's/^"//' -e 's/"$//'
  - title: Etherium price
    position: [[0, 0], [80, 20]]
    rate-ms: 300000
    legend:
        enabled: false
        details: false
    scale: 0
    items:
      - label: Etherium
        color: 39
        sample: curl -s 'https://api.binance.com/api/v3/avgPrice?symbol=ETHUSDT' |
            jq '.price' | sed -e 's/^"//' -e 's/"$//'
